import pandas as pd
import os

path = "output/ml_prepared_traffic.csv"
print("=== Output File Verification ===")
print("File exists:", os.path.exists(path))
print("File size (bytes):", os.path.getsize(path))

df = pd.read_csv(path)
print("Total records:", f"{len(df):,}")
print("Columns:", list(df.columns))
print("\ndtypes:")
print(df.dtypes)
print("\nNull values per column:")
print(df.isnull().sum())
print("\nUnique sensors:", df["sensor_id"].nunique())
print("Timestamp min:", df["timestamp"].min())
print("Timestamp max:", df["timestamp"].max())
print()
print("=== First 5 records ===")
print(df.head(5).to_string())
print()
print("=== Last 5 records ===")
print(df.tail(5).to_string())
print()
print("=== Sample sensor 771667 (lowest ref speed ~28 mph) ===")
print(df[df["sensor_id"] == 771667].head(3).to_string())
print()
print("=== Congestion class distribution ===")
print(df["congestion_class"].value_counts())
print()
print("=== current_speed zero-speed check ===")
print("Zero-speed records:", int((df["current_speed"] == 0.0).sum()))
print("Negative current_speed records:", int((df["current_speed"] < 0).sum()))
print()
print("=== sensor_id range ===")
print("Min sensor_id:", df["sensor_id"].min())
print("Max sensor_id:", df["sensor_id"].max())
